a, a → ¬b ⊢ b                     ;
a, a → b ⊢ b                      ;
a, a → b ⊢ a ∨ b                  ;
b ⊢ ¬b                            ;
a ∧ b ∧ ¬a ∨ b ⊢ a                ;
¬b ↔ a ∧ b ⊢ a                    ;
a ∧ b, b ∧ ¬c ⊢ a ∨ c             ;
a ∧ b, b ∧ ¬c ⊢ a ∧ ¬c            ;
a ∧ b, b ∧ ¬c ⊢ a ∧ c             ;
a → b → a ⊢ a                     ;
a → b ∧ b → c, a ⊢ c              ;
(a → b) ∧ (b → c), a ⊢ c          ;
a ↔ ¬a ⊢ F                        ;
a ↔ ¬a ⊢ b                        ;
A and B and (not A or B) proves A ;
A and B iff not B leads to A      ;
